name: C/C++ CI

on: [push]

jobs:
  build:
    name: Caboose Build on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
#         os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./build.sh
